[build]
  command = "npm run build"
  publish = "build"

[[headers]]
  for = "/**/*.js"
  [headers.values]
    Content-Type = "application/javascript"

[[headers]]
  for = "/**/*.mjs"
  [headers.values]
    Content-Type = "application/javascript"